Ajax 2
JakuninOleg/qna pull request #5
Opened 2018-05-08 08:31 UTC by JakuninOleg

2018-05-10 07:56 UTC, vkurennov requested changes

2018-05-10 07:56 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def update
Нужна проверка на автора

2018-05-10 07:56 UTC, vkurennov commented on spec/acceptance/answers/set_best_answer_spec.rb
> +  describe 'Authenticated user' do
Нужно также проверить, что лучший ответ выводится первым

2018-05-10 07:56 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +  describe 'PATCH #update' do
Тут должно быть 2 контекста: для автора и для не автора

2018-05-10 07:56 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +      it "User tries to edit someone else's question" do
Также надо еще проверить, какой в этом случае рендер/редирект

2018-05-10 09:47 UTC, JakuninOleg commented on spec/acceptance/answers/set_best_answer_spec.rb
> +  describe 'Authenticated user' do
А как это сделать в acceptance тесте? Что-то не нашёл селектора, который поможет тут

2018-05-11 07:56 UTC, vkurennov commented on spec/acceptance/answers/set_best_answer_spec.rb
> +  describe 'Authenticated user' do
Используй  css псевдо-класс `:first`

2018-05-11 08:15 UTC, vkurennov requested changes

2018-05-11 08:15 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to @answer.question
Это ajax-запрос, тут нет смысла делать редирект, он пройдет в фоне, но браузер пользователю ничего не отобразит. Нужно ошибки показывать так, как в create

2018-05-11 08:15 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to @question
удаление тоже через ajax, так что редирект тут тоже не имеет смысла

2018-05-11 08:15 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +      redirect_to @question
Редирект при ajax-запросах не имеет смысла

2018-05-12 10:24 UTC, vkurennov approved these changes

2018-05-14 09:13 UTC, merged